### ISSUE TITLE
Auto-give book to player

### ISSUE THREAD

**Issue by rckymtnrfc** [Vexatos/RTFM#4]
Would you consider adding a feature to give the player a book when they first enter the world?  

Thanks!

**Comment by Vexatos** [comment]
I am pretty sure that there are other mods that can do that, but I might look into it.

**Comment by rckymtnrfc** [comment]
I'm not sure any of the mods like Initial Inventory or Starting Inventory have been updated to 1.12, which is why I thought you might consider adding that feature.  Thanks!
