### ISSUE TITLE
[request] Multiple books

### ISSUE THREAD

**Issue by Ash70** [Vexatos/RTFM#5]
Would it be possible to add multiple books?

**Comment by asiekierka** [comment]
(And could this include other mods providing their own books in assets/[mod id]/rtfm?)

**Comment by talonos2** [comment]
Gonna +1 this request.

As a modpack maker (and thus your intended audience) it'd be useful to have multiple books. Different categories of info having their own books is a good way of keeping information compartmentalized and avoid overwhelming the player.

Imagine you've got three main "stages" of progression in your modpack (Ancient, Modern, Space) Having all the info on space-tier modpack changes wouldn't be useful in the Ancient age.

This sample use case is distinct from the modders who have been asking you to do this so they can give their mods manual via your API.
